services:
services:
  mem0_store:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"

  openmemory-mcp:
    image: openmemory-mcp-local
    environment:
      - OPENAI_API_KEY=
      - GOOGLE_API_KEY=AIzaSyDRYGIT7I-2mhKEsnRZuw_eQ7pbSDnVEVw
      - LLM_PROVIDER=gemini
      - USER=David
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - openmemory_db:/usr/src/openmemory/data

volumes:
  qdrant_data:
  openmemory_db:
